version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guira-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
